name: AppConfig-tf
summary: This is an App Configuration deployment using Terraform.
description: Deploys an App Config.
templatePath: main.tf
parameters:
- id: "name"
  name: "name"
  description: "Name of the App Config"
  type: "string"
  required: true
- id: "location"
  name: "location"
  description: "Location to deploy the environment resources"
  default: "westus3"
  type: "string"
runner: Terraform