# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: WebApp-tf
version: 1.0.0
summary: Azure Web App Environment (Terraform)
description: Deploys an Azure Web App without a data store
templatePath: main.tf
runner: "jleemngenvmcap.azurecr.io/ade-terraform-extensibility:latest"

parameters:
  - id: name
    name: Name
    description: 'Name of the Web App.'
    type: string
    required: true
  - id: location
    name: Location
    description: 'Location to deploy the environment resources'
    type: string
    default: 'westus3'
  - id: remote_state_rg
    name: Remote State Resource Group
    description: 'Resource Group to store the remote state'
    type: string
    allowed:
    - ade-sandbox-rg  
    required: true
  - id: remote_state_sa
    name: Remote State Storage Account
    description: 'Storage Account to store the remote state'
    type: string
    required: true
    allowed:
    - adesandboxtfstatewus2 